export const DELETE_STUDENT = 'DELETE_STUDENT';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';

export const ADD_STUDENT = 'ADD_STUDENT';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';